/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoanUploadDocumentsRouteImport } from './routes/loan/upload-documents'
import { Route as LoanPreliminaryInfoRouteImport } from './routes/loan/preliminary-info'
import { Route as LoanCustomerIdentifyRouteImport } from './routes/loan/customer-identify'
import { Route as LoanCustomerAssetDetailRouteImport } from './routes/loan/customer-asset-detail'

const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanUploadDocumentsRoute = LoanUploadDocumentsRouteImport.update({
  id: '/loan/upload-documents',
  path: '/loan/upload-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanPreliminaryInfoRoute = LoanPreliminaryInfoRouteImport.update({
  id: '/loan/preliminary-info',
  path: '/loan/preliminary-info',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCustomerIdentifyRoute = LoanCustomerIdentifyRouteImport.update({
  id: '/loan/customer-identify',
  path: '/loan/customer-identify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCustomerAssetDetailRoute = LoanCustomerAssetDetailRouteImport.update({
  id: '/loan/customer-asset-detail',
  path: '/loan/customer-asset-detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/setting': typeof SettingRoute
  '/loan/customer-asset-detail': typeof LoanCustomerAssetDetailRoute
  '/loan/customer-identify': typeof LoanCustomerIdentifyRoute
  '/loan/preliminary-info': typeof LoanPreliminaryInfoRoute
  '/loan/upload-documents': typeof LoanUploadDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/setting': typeof SettingRoute
  '/loan/customer-asset-detail': typeof LoanCustomerAssetDetailRoute
  '/loan/customer-identify': typeof LoanCustomerIdentifyRoute
  '/loan/preliminary-info': typeof LoanPreliminaryInfoRoute
  '/loan/upload-documents': typeof LoanUploadDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/setting': typeof SettingRoute
  '/loan/customer-asset-detail': typeof LoanCustomerAssetDetailRoute
  '/loan/customer-identify': typeof LoanCustomerIdentifyRoute
  '/loan/preliminary-info': typeof LoanPreliminaryInfoRoute
  '/loan/upload-documents': typeof LoanUploadDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/home'
    | '/login'
    | '/setting'
    | '/loan/customer-asset-detail'
    | '/loan/customer-identify'
    | '/loan/preliminary-info'
    | '/loan/upload-documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/home'
    | '/login'
    | '/setting'
    | '/loan/customer-asset-detail'
    | '/loan/customer-identify'
    | '/loan/preliminary-info'
    | '/loan/upload-documents'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/home'
    | '/login'
    | '/setting'
    | '/loan/customer-asset-detail'
    | '/loan/customer-identify'
    | '/loan/preliminary-info'
    | '/loan/upload-documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SettingRoute: typeof SettingRoute
  LoanCustomerAssetDetailRoute: typeof LoanCustomerAssetDetailRoute
  LoanCustomerIdentifyRoute: typeof LoanCustomerIdentifyRoute
  LoanPreliminaryInfoRoute: typeof LoanPreliminaryInfoRoute
  LoanUploadDocumentsRoute: typeof LoanUploadDocumentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/upload-documents': {
      id: '/loan/upload-documents'
      path: '/loan/upload-documents'
      fullPath: '/loan/upload-documents'
      preLoaderRoute: typeof LoanUploadDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/preliminary-info': {
      id: '/loan/preliminary-info'
      path: '/loan/preliminary-info'
      fullPath: '/loan/preliminary-info'
      preLoaderRoute: typeof LoanPreliminaryInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/customer-identify': {
      id: '/loan/customer-identify'
      path: '/loan/customer-identify'
      fullPath: '/loan/customer-identify'
      preLoaderRoute: typeof LoanCustomerIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/customer-asset-detail': {
      id: '/loan/customer-asset-detail'
      path: '/loan/customer-asset-detail'
      fullPath: '/loan/customer-asset-detail'
      preLoaderRoute: typeof LoanCustomerAssetDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SettingRoute: SettingRoute,
  LoanCustomerAssetDetailRoute: LoanCustomerAssetDetailRoute,
  LoanCustomerIdentifyRoute: LoanCustomerIdentifyRoute,
  LoanPreliminaryInfoRoute: LoanPreliminaryInfoRoute,
  LoanUploadDocumentsRoute: LoanUploadDocumentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
